---

- name: Create new EC2 key pair
  ec2_key:
    name: ec2_homework13_ssh_key
    region: "{{ region }}"
    wait: True
  register: ec2_key

- name: Save private key
  copy: > 
    content="{{ ec2_key.key.private_key }}" 
    dest="./keys/ec2_homework13_ssh_key.pem" 
    mode=0600
  when: ec2_key.changed

- name: Create security group
  ec2_group:
    name: sec-group-for-all
    region: "{{ region }}"
    vpc_id: vpc-0439e748584867b98
    description: "desc"
    rules:
      - proto: all
        cidr_ip: 0.0.0.0/0
        from_port: -1
        to_port: -1
  register: ec2_group

- name: Add instance
  ec2:
    key_name: ec2_homework13_ssh_key
    region: "{{ region }}"
    group_id: "{{ ec2_group.group_id }}"
    instance_type: t2.micro
    image: "{{ image }}"
    wait: yes
    exact_count: 1
    count_tag: 
      type: "{{ group }}"
    instance_tags:
      type: "{{ group }}"
  register: ec2
  when: group not in groups

- name: Instance wait
  wait_for: host={{ item.public_dns_name }} port=22 delay=10 state=started search_regex=OpenSSH
  with_items: "{{ ec2.instances }}"
  when: group not in groups

- name: Add host
  add_host:
    name: "{{ item.public_dns_name }}"
    groups: 
      - "{{ group }}"
  with_items: "{{ ec2.instances }}"
  when: group not in groups
