pipeline {
    parameters {
        password (name: 'AWS_ACCESS_KEY_ID')
        password (name: 'AWS_SECRET_ACCESS_KEY')
    }
    environment {
        TF_VAR_AWS_ACCESS_KEY_ID = "${params.AWS_ACCESS_KEY_ID}"
        TF_VAR_AWS_SECRET_ACCESS_KEY = "${params.AWS_SECRET_ACCESS_KEY}"
    }

    agent any
    stages {
        stage("Deploy") {
            agent {
                docker {
                    image "jenkins-agent:latest"
                    args '-v /var/run/docker.sock:/var/run/docker.sock'
                    reuseNode true
                    label "jenkins-agent"
                }
            }
            steps {
                echo "Build start"
                sh "pwd"
                sh "ls -al"
                sh "terraform -chdir=certwork/terraform init -var='AWS_ACCESS_KEY_ID=${params.AWS_ACCESS_KEY_ID}' -var='AWS_SECRET_ACCESS_KEY=${params.AWS_SECRET_ACCESS_KEY}'"
                // sh "terraform -chdir=certwork/terraform plan"
            }
        }
    }
}
