pipeline {
    agent any
    stages {
        stage("Build") {
            agent {
                docker {
                    image "jenkins-agent:latest"
                    args '-v /var/run/docker.sock:/var/run/docker.sock'
                    reuseNode true
                    label "jenkins-agent"
                }
            }
            steps {
                echo "Build start"
                sh "pwd"
                sh "ls -al"
                sh "terraform -chdir=certwork/terraform init"
                sh "terraform -chdir=certwork/terraform plan"
            }
        }
        stage("Test") {
            steps {
                echo "Test Success!"
            }
        }
        stage("Deploy" ) {
            steps {
                echo "Deploy"
            }
        }
    }
}
