pipeline {
    agent any
    stages {
        stage("Build") {
            steps {
                echo "Build start"
                sh "terraform -chdir=certwork/terraform init"
                sh "terraform -chdir=certwork/terraform plan"
            }
        }
        stage("Test") {
            steps {
                echo "Test Success!"
            }
        }
        stage("Deploy" ) {
            steps {
                echo "Deploy"
            }
        }
    }
}
