---
- name: commons
  hosts: servers
  become: yes

  roles:
    - commons
         
- name: build
  hosts: build
  become: yes

  roles:
    - build

- name: deploy
  hosts: deploy
  become: yes

  roles:
    - deploy

- name: build app
  hosts: build
  become: yes

  tasks:

  - name: Ensure project is present
    ansible.builtin.git:
      repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello'
      dest: /opt/project
      clone: yes
      update: yes

  - name: Ensure project is build
    command: 'mvn -f /opt/project package'

- name: deploy app
  hosts: deploy
  become: yes

  tasks:

  - name: Ensure project is deploy
    synchronize:
      src: /opt/project/target/hello-1.0.war
      dest: /var/lib/tomcat9/webapps/
    delegate_to: server-2



