---
- name: commons
  hosts: servers
  become: yes

  roles:
    - commons
         
- name: build
  hosts: build
  become: yes

  roles:
    - build

- name: deploy
  hosts: deploy
  become: yes

  roles:
    - deploy
