---
- name: Create buld servers
  hosts: local
  roles: 
    - role: ec2
      vars:
        region: eu-central-1
        image: ami-0d527b8c289b4af7f
        group: build

- name: Create prod servers
  hosts: local
  roles: 
    - role: ec2
      vars:
        region: eu-central-1
        image: ami-0d527b8c289b4af7f
        group: prod

- name: Build settings
  hosts: build
  become: true
  roles:
    - build

- name: Deploty settings
  hosts: prod
  become: true
  roles:
    - deploy

- name: build app
  hosts: build
  become: yes

  tasks:

    - name: Ensure project is present
      ansible.builtin.git:
        repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello'
        dest: /opt/project
        clone: yes
        update: yes

    - name: Ensure project is build
      command: 'mvn -f /opt/project package'

    - name: Copy file from build
      fetch:
        src: /opt/project/target/hello-1.0.war
        dest: tmp/hello.war
        flat: yes

- name: deploy app
  hosts: prod
  become: yes

  tasks:

    - name: Copy file to prod
      copy:
        src: tmp/hello.war
        dest: /var/lib/tomcat9/webapps/