pipeline {
     options {
        buildDiscarder(
            logRotator(
                artifactDaysToKeepStr: "",
                artifactNumToKeepStr: "",
                daysToKeepStr: "",
                numToKeepStr: "10"
            )
        )
        disableConcurrentBuilds()
    }

    agent {
        node {
            label 'docker'
        }
    }
    stages {
        stage("Prepare build") {
            steps {
                echo "Prepare build"
                sh "docker build -f homework11/JenkinsAgentDockerfile . -t project-build"
            }
        }
        stage("Build") {
            agent {
                docker {
                    image "project-build"
                    reuseNode true
                    label "build-image"
                }
            }
            steps {
                echo "Build start"
                sh 'sleep 3'
                sh "docker build -f homework11/ProjectBuildDockerfile . -t app-build"
                sh "docker build -f homework11/ProjectDeployDockerfile . -t app-deploy"
            }
        }
        stage("Test") {
            steps {
                echo "Test Success!"
            }
        }
        stage("Deploy" ) {
            steps {
                echo "Deploy"
            }
        }
    }
}