pipeline {
    agent {
        node {
            label 'docker'
        }
    }
    stages {
        stage("Prepare build") {
            steps {
                echo "Prepare build"
                sh 'id'
                sh 'ip address'
                sh "docker build -f homework11/JenkinsAgentDockerfile . -t project-build"
            }
        }
        stage("Build") {
            // agent {
            //     docker {
            //         image "project-build"
            //     }
            // }
            steps {
                echo "Build start"
                sh 'node --version'
            }
        }
        stage("Test") {
            steps {
                echo "Test Success!"
            }
        }
        stage("Deploy" ) {
            steps {
                echo "Deploy"
            }
        }
    }
}