pipeline {
    agent {
        docker {
            image "node:16.13.1-alpine"
        }
    }
    stages {
        stage("Build") {
            steps {
                echo "Git clone project"
            }
        }
        stage("Test") {
            steps {
                echo "Test Success!"
                sh 'node --version'
            }
        }
        stage("Deploy" ) {
            steps {
                echo "Deploy"
            }
        }
    }
}