---

- name: Build project
  hosts: build
  become: yes

  tasks:
  - name: Ensure maven package is present
    apt:
      name: maven
      state: present

  - name: Ensure git package is present
    apt:
      name: git-core
      state: present

  - name: Ensure jdk package is present
    apt:
      name: default-jdk
      state: present

  - name: Ensure project is present
    ansible.builtin.git:
      repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello'
      dest: /opt/project
      clone: yes
      update: yes

  - name: Ensure project is build
    command: 'mvn -f /opt/project package'


- name: Deploy project
  hosts: prod
  become: yes

  tasks:

  - name: Ensure tomcat9 package is present
    apt:
      name: tomcat9
      state: present

  - name: Ensure project is deploy
    synchronize:
      src: /opt/project/target/hello-1.0.war
      dest: /var/lib/tomcat9/webapps/
    delegate_to: server-2
