---

- name: Build configure
  hosts: build
  become: yes
  roles:
    - base

- name: Staging configure
  hosts: staging
  become: yes
  roles:
    - base

    
- name: Build
  hosts: build
  become: yes

  tasks:

    - name: Project source is present
      ansible.builtin.git:
        repo: 'https://github.com/paladim/devops'
        dest: /opt/project
        clone: yes
        update: yes


    - name: Build container
      shell:
        cmd: "docker build -f /opt/project/homework11/ProjectBuildDockerfile . -t app-build:latest"

    - name: Deploy container
      shell:
        cmd: "docker build -f /opt/project/homework11/ProjectDeployDockerfile . -t app-deploy:latest"

    - name: Tag container
      shell:
        cmd: "docker tag app-deploy:latest {{ account_id.Account }}.dkr.ecr.eu-central-1.amazonaws.com/app:latest"

    - name: Push container
      shell:
        cmd: "docker push {{ account_id.Account }}.dkr.ecr.eu-central-1.amazonaws.com/app:latest"

- name: Deploy
  hosts: staging
  become: yes

  tasks:

    - name: Remove container
      shell:
        cmd: "docker rm app -f"

    - name: Pull container
      shell:
        cmd: "docker pull {{ account_id.Account }}.dkr.ecr.eu-central-1.amazonaws.com/app:latest"

    - name: Run container
      shell:
        cmd: "docker run -d -p 8080:8080 --name app {{ account_id.Account }}.dkr.ecr.eu-central-1.amazonaws.com/app:latest"

